---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  # client_rb:
  #   treat_deprecation_warnings_as_errors: true # WiP on some depends

platforms:
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.10
  run_list: ["recipe[apt]"]
- name: debian-7.8
  run_list: ["recipe[apt]"]
- name: debian-8.7
  run_list: ["recipe[apt]"]
- name: centos-6.6
  run_list: ["recipe[selinux::disabled]"]
- name: centos-7.0
  run_list: ["recipe[selinux::disabled]"]
- name: fedora-20
  run_list: ["recipe[selinux::disabled]"]

suites:
- name: mysql
  run_list:
  - recipe[minitest-handler]
  - recipe[postfix-dovecot_test]
  # excludes:
  # From postfixadmin cookbook:
  # - centos-7
  # - centos-7.0
  # - ubuntu-12.04
  # - ubuntu-14.04
  # - ubuntu-16.04
  # - ubuntu-16.10
- name: postgresql
  excludes:
  - amazon-2011.02.1
  - amazon-2013.09.2
  # From postfixadmin cookbook:
  # - centos-7
  # - centos-7.0
  # - scientific-6.6
  # - ubuntu-16.04
  # - ubuntu-16.10
  run_list:
  - recipe[minitest-handler]
  - recipe[postfix-dovecot_test]
  attributes:
    postfix-dovecot:
      database:
        type: postgresql
- name: postfixpgsql
  excludes:
  - amazon-2011.02.1
  - amazon-2013.09.2
  # - ubuntu-10.04
  # - ubuntu-12.04
  # - debian-6.0.10
  # - debian-7.8
  # - centos-6.6
  # - fedora-20
  run_list:
  - recipe[postfix-dovecot_test::postfix_postgresql]
